apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-2022-backend-deployment
  labels:
    app: my-apppppppppppp
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      tier: backend
  template:
    metadata:
      labels:
        app: my-app
        tier: backend
    spec:
      containers:
      - name: devops-project-2022-backend-container
        image: {{ .Values.backenddeployment.image }}:{{ .Values.backenddeployment.tag }}
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_USER
          value: admin
        - name: MONGODB_PASSWORD
          value: admin
        - name: MONGODB_HOST
          value: devops-project-2022-mongodb-service
      restartPolicy: Always