apiVersion: v1
kind: Service
metadata:
  name: devops-project-2022-mongodb-service
spec:
  selector:
    app: my-app
    tier: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017